version: "3"
services:
  itrepair:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      DB_HOST: mysqldb
      DB_NAME: springdb
      DB_USER: root
      DB_PASSWORD : testtest


  mysql-db:
    image: akoller/low-memory-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: testtest
      MYSQL_DATABASE: springdb
      #... other properties