   version: "3"
    services:
      spring-boot-service:
        image: itrepair
        build:
          context: .
        ports:
          - 8080:8080
        environment:
          DB_HOST: mysqldb
          DB_NAME: springdb
          DB_USER:
          DB_PASSWORD:
        networks:
          - employee-mysql
        depends_on:
          - mysqldb


      mysqldb:
        image: mysql:8
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: "testtest"
          MYSQL_DATABASE: springdb
          networks:
            employee-mysql:
